# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/jxfzwar/Documents/PyUi/gaoyiwen/ui.ui'
#
# Created by: PyQt4 UI code generator 4.12
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GaoYiWen(object):
    def setupUi(self, GaoYiWen):
        GaoYiWen.setObjectName(_fromUtf8("GaoYiWen"))
        GaoYiWen.resize(480, 720)
        GaoYiWen.setSizeGripEnabled(True)
        self.label = QtGui.QLabel(GaoYiWen)
        self.label.setGeometry(QtCore.QRect(130, 10, 220, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.selectagain = QtGui.QPushButton(GaoYiWen)
        self.selectagain.setGeometry(QtCore.QRect(20, 680, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.selectagain.setFont(font)
        self.selectagain.setWhatsThis(_fromUtf8(""))
        self.selectagain.setObjectName(_fromUtf8("selectagain"))
        self.nextday = QtGui.QPushButton(GaoYiWen)
        self.nextday.setGeometry(QtCore.QRect(380, 680, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nextday.setFont(font)
        self.nextday.setObjectName(_fromUtf8("nextday"))
        self.good_gaoyiwen = QtGui.QLabel(GaoYiWen)
        self.good_gaoyiwen.setGeometry(QtCore.QRect(20, 350, 81, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.good_gaoyiwen.setFont(font)
        self.good_gaoyiwen.setObjectName(_fromUtf8("good_gaoyiwen"))
        self.good_xiaosao = QtGui.QLabel(GaoYiWen)
        self.good_xiaosao.setGeometry(QtCore.QRect(20, 400, 71, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.good_xiaosao.setFont(font)
        self.good_xiaosao.setObjectName(_fromUtf8("good_xiaosao"))
        self.good_yiwensheshou = QtGui.QLabel(GaoYiWen)
        self.good_yiwensheshou.setGeometry(QtCore.QRect(20, 450, 121, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.good_yiwensheshou.setFont(font)
        self.good_yiwensheshou.setObjectName(_fromUtf8("good_yiwensheshou"))
        self.good_gaozong = QtGui.QLabel(GaoYiWen)
        self.good_gaozong.setGeometry(QtCore.QRect(20, 500, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.good_gaozong.setFont(font)
        self.good_gaozong.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.good_gaozong.setObjectName(_fromUtf8("good_gaozong"))
        self.goods = QtGui.QLabel(GaoYiWen)
        self.goods.setGeometry(QtCore.QRect(20, 320, 61, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.goods.setFont(font)
        self.goods.setObjectName(_fromUtf8("goods"))
        self.price = QtGui.QLabel(GaoYiWen)
        self.price.setGeometry(QtCore.QRect(140, 320, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.price.setFont(font)
        self.price.setObjectName(_fromUtf8("price"))
        self.updown = QtGui.QLabel(GaoYiWen)
        self.updown.setGeometry(QtCore.QRect(200, 320, 81, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.updown.setFont(font)
        self.updown.setObjectName(_fromUtf8("updown"))
        self.number = QtGui.QLabel(GaoYiWen)
        self.number.setGeometry(QtCore.QRect(290, 320, 81, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.number.setFont(font)
        self.number.setObjectName(_fromUtf8("number"))
        self.buy = QtGui.QLabel(GaoYiWen)
        self.buy.setGeometry(QtCore.QRect(370, 320, 41, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.buy.setFont(font)
        self.buy.setObjectName(_fromUtf8("buy"))
        self.sell = QtGui.QLabel(GaoYiWen)
        self.sell.setGeometry(QtCore.QRect(420, 320, 41, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.sell.setFont(font)
        self.sell.setObjectName(_fromUtf8("sell"))
        self.price1 = QtGui.QLabel(GaoYiWen)
        self.price1.setGeometry(QtCore.QRect(150, 350, 21, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.price1.setFont(font)
        self.price1.setObjectName(_fromUtf8("price1"))
        self.price2 = QtGui.QLabel(GaoYiWen)
        self.price2.setGeometry(QtCore.QRect(150, 400, 21, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.price2.setFont(font)
        self.price2.setObjectName(_fromUtf8("price2"))
        self.price3 = QtGui.QLabel(GaoYiWen)
        self.price3.setGeometry(QtCore.QRect(150, 450, 31, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.price3.setFont(font)
        self.price3.setObjectName(_fromUtf8("price3"))
        self.price4 = QtGui.QLabel(GaoYiWen)
        self.price4.setGeometry(QtCore.QRect(150, 500, 31, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.price4.setFont(font)
        self.price4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.price4.setObjectName(_fromUtf8("price4"))
        self.updown1 = QtGui.QLabel(GaoYiWen)
        self.updown1.setGeometry(QtCore.QRect(200, 350, 81, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.updown1.setFont(font)
        self.updown1.setAlignment(QtCore.Qt.AlignCenter)
        self.updown1.setObjectName(_fromUtf8("updown1"))
        self.updown2 = QtGui.QLabel(GaoYiWen)
        self.updown2.setGeometry(QtCore.QRect(200, 400, 81, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.updown2.setFont(font)
        self.updown2.setAlignment(QtCore.Qt.AlignCenter)
        self.updown2.setObjectName(_fromUtf8("updown2"))
        self.updown3 = QtGui.QLabel(GaoYiWen)
        self.updown3.setGeometry(QtCore.QRect(200, 450, 81, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.updown3.setFont(font)
        self.updown3.setAlignment(QtCore.Qt.AlignCenter)
        self.updown3.setObjectName(_fromUtf8("updown3"))
        self.updown4 = QtGui.QLabel(GaoYiWen)
        self.updown4.setGeometry(QtCore.QRect(200, 500, 81, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.updown4.setFont(font)
        self.updown4.setAlignment(QtCore.Qt.AlignCenter)
        self.updown4.setObjectName(_fromUtf8("updown4"))
        self.number1 = QtGui.QLabel(GaoYiWen)
        self.number1.setGeometry(QtCore.QRect(290, 350, 71, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.number1.setFont(font)
        self.number1.setAlignment(QtCore.Qt.AlignCenter)
        self.number1.setObjectName(_fromUtf8("number1"))
        self.number2 = QtGui.QLabel(GaoYiWen)
        self.number2.setGeometry(QtCore.QRect(290, 400, 71, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.number2.setFont(font)
        self.number2.setAlignment(QtCore.Qt.AlignCenter)
        self.number2.setObjectName(_fromUtf8("number2"))
        self.number3 = QtGui.QLabel(GaoYiWen)
        self.number3.setGeometry(QtCore.QRect(290, 450, 71, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.number3.setFont(font)
        self.number3.setAlignment(QtCore.Qt.AlignCenter)
        self.number3.setObjectName(_fromUtf8("number3"))
        self.number4 = QtGui.QLabel(GaoYiWen)
        self.number4.setGeometry(QtCore.QRect(290, 500, 71, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.number4.setFont(font)
        self.number4.setAlignment(QtCore.Qt.AlignCenter)
        self.number4.setObjectName(_fromUtf8("number4"))
        self.buy1 = QtGui.QSpinBox(GaoYiWen)
        self.buy1.setGeometry(QtCore.QRect(360, 350, 45, 30))
        self.buy1.setObjectName(_fromUtf8("buy1"))
        self.sell1 = QtGui.QSpinBox(GaoYiWen)
        self.sell1.setGeometry(QtCore.QRect(420, 350, 45, 30))
        self.sell1.setObjectName(_fromUtf8("sell1"))
        self.buy2 = QtGui.QSpinBox(GaoYiWen)
        self.buy2.setGeometry(QtCore.QRect(360, 400, 45, 30))
        self.buy2.setObjectName(_fromUtf8("buy2"))
        self.buy3 = QtGui.QSpinBox(GaoYiWen)
        self.buy3.setGeometry(QtCore.QRect(360, 450, 45, 30))
        self.buy3.setObjectName(_fromUtf8("buy3"))
        self.buy4 = QtGui.QSpinBox(GaoYiWen)
        self.buy4.setGeometry(QtCore.QRect(360, 500, 45, 30))
        self.buy4.setObjectName(_fromUtf8("buy4"))
        self.sell2 = QtGui.QSpinBox(GaoYiWen)
        self.sell2.setGeometry(QtCore.QRect(420, 400, 45, 30))
        self.sell2.setObjectName(_fromUtf8("sell2"))
        self.sell3 = QtGui.QSpinBox(GaoYiWen)
        self.sell3.setGeometry(QtCore.QRect(420, 450, 45, 30))
        self.sell3.setObjectName(_fromUtf8("sell3"))
        self.sell4 = QtGui.QSpinBox(GaoYiWen)
        self.sell4.setGeometry(QtCore.QRect(420, 500, 45, 30))
        self.sell4.setObjectName(_fromUtf8("sell4"))
        self.line1 = QtGui.QFrame(GaoYiWen)
        self.line1.setGeometry(QtCore.QRect(10, 310, 461, 20))
        self.line1.setFrameShape(QtGui.QFrame.HLine)
        self.line1.setFrameShadow(QtGui.QFrame.Sunken)
        self.line1.setObjectName(_fromUtf8("line1"))
        self.line2 = QtGui.QFrame(GaoYiWen)
        self.line2.setGeometry(QtCore.QRect(10, 530, 461, 20))
        self.line2.setFrameShape(QtGui.QFrame.HLine)
        self.line2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line2.setObjectName(_fromUtf8("line2"))
        self.moneyleftlabel = QtGui.QLabel(GaoYiWen)
        self.moneyleftlabel.setGeometry(QtCore.QRect(20, 580, 221, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.moneyleftlabel.setFont(font)
        self.moneyleftlabel.setObjectName(_fromUtf8("moneyleftlabel"))
        self.placeleftlabel = QtGui.QLabel(GaoYiWen)
        self.placeleftlabel.setGeometry(QtCore.QRect(20, 610, 221, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.placeleftlabel.setFont(font)
        self.placeleftlabel.setObjectName(_fromUtf8("placeleftlabel"))
        self.moneyleft = QtGui.QLabel(GaoYiWen)
        self.moneyleft.setGeometry(QtCore.QRect(360, 580, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.moneyleft.setFont(font)
        self.moneyleft.setAlignment(QtCore.Qt.AlignCenter)
        self.moneyleft.setObjectName(_fromUtf8("moneyleft"))
        self.placeleft = QtGui.QLabel(GaoYiWen)
        self.placeleft.setGeometry(QtCore.QRect(360, 610, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.placeleft.setFont(font)
        self.placeleft.setAlignment(QtCore.Qt.AlignCenter)
        self.placeleft.setObjectName(_fromUtf8("placeleft"))
        self.check = QtGui.QPushButton(GaoYiWen)
        self.check.setGeometry(QtCore.QRect(360, 550, 101, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.check.setFont(font)
        self.check.setObjectName(_fromUtf8("check"))
        self.line3 = QtGui.QFrame(GaoYiWen)
        self.line3.setGeometry(QtCore.QRect(10, 660, 461, 20))
        self.line3.setFrameShape(QtGui.QFrame.HLine)
        self.line3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line3.setObjectName(_fromUtf8("line3"))
        self.afterbuyandsell = QtGui.QLabel(GaoYiWen)
        self.afterbuyandsell.setGeometry(QtCore.QRect(20, 550, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.afterbuyandsell.setFont(font)
        self.afterbuyandsell.setObjectName(_fromUtf8("afterbuyandsell"))
        self.storagelabel = QtGui.QLabel(GaoYiWen)
        self.storagelabel.setGeometry(QtCore.QRect(20, 200, 71, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.storagelabel.setFont(font)
        self.storagelabel.setObjectName(_fromUtf8("storagelabel"))
        self.levellable = QtGui.QLabel(GaoYiWen)
        self.levellable.setGeometry(QtCore.QRect(20, 230, 51, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.levellable.setFont(font)
        self.levellable.setObjectName(_fromUtf8("levellable"))
        self.remainplacelabel = QtGui.QLabel(GaoYiWen)
        self.remainplacelabel.setGeometry(QtCore.QRect(20, 290, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.remainplacelabel.setFont(font)
        self.remainplacelabel.setObjectName(_fromUtf8("remainplacelabel"))
        self.remainplace = QtGui.QLabel(GaoYiWen)
        self.remainplace.setGeometry(QtCore.QRect(360, 290, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(False)
        self.remainplace.setFont(font)
        self.remainplace.setAlignment(QtCore.Qt.AlignCenter)
        self.remainplace.setObjectName(_fromUtf8("remainplace"))
        self.line4 = QtGui.QFrame(GaoYiWen)
        self.line4.setGeometry(QtCore.QRect(10, 190, 461, 20))
        self.line4.setFrameShape(QtGui.QFrame.HLine)
        self.line4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line4.setObjectName(_fromUtf8("line4"))
        self.pocketmoney = QtGui.QLabel(GaoYiWen)
        self.pocketmoney.setGeometry(QtCore.QRect(20, 100, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.pocketmoney.setFont(font)
        self.pocketmoney.setObjectName(_fromUtf8("pocketmoney"))
        self.moneyleft_2 = QtGui.QLabel(GaoYiWen)
        self.moneyleft_2.setGeometry(QtCore.QRect(360, 100, 101, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.moneyleft_2.setFont(font)
        self.moneyleft_2.setAlignment(QtCore.Qt.AlignCenter)
        self.moneyleft_2.setObjectName(_fromUtf8("moneyleft_2"))
        self.placeleft_2 = QtGui.QLabel(GaoYiWen)
        self.placeleft_2.setGeometry(QtCore.QRect(360, 140, 101, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.placeleft_2.setFont(font)
        self.placeleft_2.setAlignment(QtCore.Qt.AlignCenter)
        self.placeleft_2.setObjectName(_fromUtf8("placeleft_2"))
        self.emptyplace = QtGui.QLabel(GaoYiWen)
        self.emptyplace.setGeometry(QtCore.QRect(20, 140, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.emptyplace.setFont(font)
        self.emptyplace.setObjectName(_fromUtf8("emptyplace"))
        self.line5 = QtGui.QFrame(GaoYiWen)
        self.line5.setGeometry(QtCore.QRect(10, 30, 461, 20))
        self.line5.setFrameShape(QtGui.QFrame.HLine)
        self.line5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line5.setObjectName(_fromUtf8("line5"))
        self.marketmoney = QtGui.QLabel(GaoYiWen)
        self.marketmoney.setGeometry(QtCore.QRect(20, 120, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.marketmoney.setFont(font)
        self.marketmoney.setObjectName(_fromUtf8("marketmoney"))
        self.moneyleft_3 = QtGui.QLabel(GaoYiWen)
        self.moneyleft_3.setGeometry(QtCore.QRect(360, 120, 101, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.moneyleft_3.setFont(font)
        self.moneyleft_3.setAlignment(QtCore.Qt.AlignCenter)
        self.moneyleft_3.setObjectName(_fromUtf8("moneyleft_3"))
        self.goal = QtGui.QLabel(GaoYiWen)
        self.goal.setGeometry(QtCore.QRect(40, 40, 411, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.goal.setFont(font)
        self.goal.setObjectName(_fromUtf8("goal"))
        self.daylabel = QtGui.QLabel(GaoYiWen)
        self.daylabel.setGeometry(QtCore.QRect(20, 70, 41, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.daylabel.setFont(font)
        self.daylabel.setObjectName(_fromUtf8("daylabel"))
        self.day = QtGui.QLabel(GaoYiWen)
        self.day.setGeometry(QtCore.QRect(70, 70, 41, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.day.setFont(font)
        self.day.setObjectName(_fromUtf8("day"))
        self.name = QtGui.QLineEdit(GaoYiWen)
        self.name.setGeometry(QtCore.QRect(320, 70, 101, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name.setFont(font)
        self.name.setText(_fromUtf8(""))
        self.name.setObjectName(_fromUtf8("name"))
        self.lv1 = QtGui.QRadioButton(GaoYiWen)
        self.lv1.setGeometry(QtCore.QRect(80, 230, 91, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lv1.setFont(font)
        self.lv1.setObjectName(_fromUtf8("lv1"))
        self.lv2 = QtGui.QRadioButton(GaoYiWen)
        self.lv2.setGeometry(QtCore.QRect(220, 230, 91, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lv2.setFont(font)
        self.lv2.setObjectName(_fromUtf8("lv2"))
        self.lv3 = QtGui.QRadioButton(GaoYiWen)
        self.lv3.setGeometry(QtCore.QRect(360, 230, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lv3.setFont(font)
        self.lv3.setObjectName(_fromUtf8("lv3"))
        self.lv4 = QtGui.QRadioButton(GaoYiWen)
        self.lv4.setGeometry(QtCore.QRect(80, 250, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lv4.setFont(font)
        self.lv4.setObjectName(_fromUtf8("lv4"))
        self.lvinf = QtGui.QRadioButton(GaoYiWen)
        self.lvinf.setGeometry(QtCore.QRect(220, 250, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lvinf.setFont(font)
        self.lvinf.setObjectName(_fromUtf8("lvinf"))
        self.levelcost = QtGui.QLabel(GaoYiWen)
        self.levelcost.setGeometry(QtCore.QRect(20, 270, 301, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.levelcost.setFont(font)
        self.levelcost.setObjectName(_fromUtf8("levelcost"))
        self.namelabel = QtGui.QLabel(GaoYiWen)
        self.namelabel.setGeometry(QtCore.QRect(220, 70, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.namelabel.setFont(font)
        self.namelabel.setObjectName(_fromUtf8("namelabel"))
        self.afterdayresult = QtGui.QLabel(GaoYiWen)
        self.afterdayresult.setGeometry(QtCore.QRect(20, 160, 441, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.afterdayresult.setFont(font)
        self.afterdayresult.setObjectName(_fromUtf8("afterdayresult"))
        self.afterdayresult_2 = QtGui.QLabel(GaoYiWen)
        self.afterdayresult_2.setGeometry(QtCore.QRect(20, 630, 441, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.afterdayresult_2.setFont(font)
        self.afterdayresult_2.setObjectName(_fromUtf8("afterdayresult_2"))
        self.levelok = QtGui.QPushButton(GaoYiWen)
        self.levelok.setGeometry(QtCore.QRect(360, 270, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.levelok.setFont(font)
        self.levelok.setObjectName(_fromUtf8("levelok"))
        self.checktips = QtGui.QLabel(GaoYiWen)
        self.checktips.setGeometry(QtCore.QRect(200, 550, 161, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.checktips.setFont(font)
        self.checktips.setObjectName(_fromUtf8("checktips"))
        self.nameok = QtGui.QPushButton(GaoYiWen)
        self.nameok.setGeometry(QtCore.QRect(430, 70, 31, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nameok.setFont(font)
        self.nameok.setObjectName(_fromUtf8("nameok"))
        self.label_2 = QtGui.QLabel(GaoYiWen)
        self.label_2.setGeometry(QtCore.QRect(120, 690, 241, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(GaoYiWen)
        self.label_3.setGeometry(QtCore.QRect(130, 670, 101, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.summoney = QtGui.QLabel(GaoYiWen)
        self.summoney.setGeometry(QtCore.QRect(240, 670, 131, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.summoney.setFont(font)
        self.summoney.setAlignment(QtCore.Qt.AlignCenter)
        self.summoney.setObjectName(_fromUtf8("summoney"))

        self.retranslateUi(GaoYiWen)
        QtCore.QMetaObject.connectSlotsByName(GaoYiWen)

    def retranslateUi(self, GaoYiWen):
        GaoYiWen.setWindowTitle(_translate("GaoYiWen", "GaoYiWen", None))
        self.label.setText(_translate("GaoYiWen", "BATTLE OF GAO YI WEN", None))
        self.selectagain.setText(_translate("GaoYiWen", "Select again", None))
        self.nextday.setText(_translate("GaoYiWen", "Next day", None))
        self.good_gaoyiwen.setText(_translate("GaoYiWen", "Gao YiWen", None))
        self.good_xiaosao.setText(_translate("GaoYiWen", "Xiao Sao", None))
        self.good_yiwensheshou.setText(_translate("GaoYiWen", "YiWen SheShou", None))
        self.good_gaozong.setText(_translate("GaoYiWen", "Gao Zong", None))
        self.goods.setText(_translate("GaoYiWen", "GOODS", None))
        self.price.setText(_translate("GaoYiWen", "PRICE", None))
        self.updown.setText(_translate("GaoYiWen", "<html><head/><body><p><span style=\" color:#ff0000;\">UP</span>/<span style=\" color:#55ff00;\">DOWN</span></p></body></html>", None))
        self.number.setText(_translate("GaoYiWen", "NUMBER", None))
        self.buy.setText(_translate("GaoYiWen", "<html><head/><body><p><span style=\" color:#aa0000;\">BUY</span></p></body></html>", None))
        self.sell.setText(_translate("GaoYiWen", "<html><head/><body><p><span style=\" color:#55aa00;\">SELL</span></p></body></html>", None))
        self.price1.setText(_translate("GaoYiWen", "$1", None))
        self.price2.setText(_translate("GaoYiWen", "$5", None))
        self.price3.setText(_translate("GaoYiWen", "$10", None))
        self.price4.setText(_translate("GaoYiWen", "$20", None))
        self.updown1.setText(_translate("GaoYiWen", "0.0%", None))
        self.updown2.setText(_translate("GaoYiWen", "0.0%", None))
        self.updown3.setText(_translate("GaoYiWen", "0.0%", None))
        self.updown4.setText(_translate("GaoYiWen", "0.0%", None))
        self.number1.setText(_translate("GaoYiWen", "0", None))
        self.number2.setText(_translate("GaoYiWen", "0", None))
        self.number3.setText(_translate("GaoYiWen", "0", None))
        self.number4.setText(_translate("GaoYiWen", "0", None))
        self.moneyleftlabel.setText(_translate("GaoYiWen", "MONEY  ON YOUR POCKET", None))
        self.placeleftlabel.setText(_translate("GaoYiWen", "EMPTY PLACE ON YOUR STORAGE", None))
        self.moneyleft.setText(_translate("GaoYiWen", "$100", None))
        self.placeleft.setText(_translate("GaoYiWen", "10", None))
        self.check.setText(_translate("GaoYiWen", "Check", None))
        self.afterbuyandsell.setText(_translate("GaoYiWen", "AFTER BUY AND SELL", None))
        self.storagelabel.setText(_translate("GaoYiWen", "STORAGE", None))
        self.levellable.setText(_translate("GaoYiWen", "LEVEL ", None))
        self.remainplacelabel.setText(_translate("GaoYiWen", "REMAIN PLACE", None))
        self.remainplace.setText(_translate("GaoYiWen", "10", None))
        self.pocketmoney.setText(_translate("GaoYiWen", "MONEY ON YOUR POCKET", None))
        self.moneyleft_2.setText(_translate("GaoYiWen", "$100", None))
        self.placeleft_2.setText(_translate("GaoYiWen", "10", None))
        self.emptyplace.setText(_translate("GaoYiWen", "PLACE LEFT  ON YOUR STORAGE", None))
        self.marketmoney.setText(_translate("GaoYiWen", "MONEY  ON MARKET", None))
        self.moneyleft_3.setText(_translate("GaoYiWen", "$0", None))
        self.goal.setText(_translate("GaoYiWen", "<html><head/><body><p><span style=\" color:#0000ff;\">GOAL OF MONEY ON YOUR POCKET AND MARKET AFTER 50 DAYS : $10000</span></p></body></html>", None))
        self.daylabel.setText(_translate("GaoYiWen", "DAY", None))
        self.day.setText(_translate("GaoYiWen", "1", None))
        self.lv1.setText(_translate("GaoYiWen", "lv. 1 - 10/2", None))
        self.lv2.setText(_translate("GaoYiWen", "lv. 2 - 25/5", None))
        self.lv3.setText(_translate("GaoYiWen", "lv. 3 - 50/10", None))
        self.lv4.setText(_translate("GaoYiWen", "lv. 4 - 100/20", None))
        self.lvinf.setText(_translate("GaoYiWen", "lv. inf - inf/100", None))
        self.levelcost.setText(_translate("GaoYiWen", "<html><head/><body><p><span style=\" color:#0000ff;\">P.S. LEVEL NUMBER - MAXIMUM PLACE/COST PER DAY</span></p></body></html>", None))
        self.namelabel.setText(_translate("GaoYiWen", "YOUR NAME", None))
        self.afterdayresult.setText(_translate("GaoYiWen", "<html><head/><body><p><span style=\" color:#0000ff;\">Nothing happened! Go next day!</span></p></body></html>", None))
        self.afterdayresult_2.setText(_translate("GaoYiWen", "<html><head/><body><p><span style=\" color:#0000ff;\">No problem! You can click next day or select again!</span></p></body></html>", None))
        self.levelok.setText(_translate("GaoYiWen", "OK", None))
        self.checktips.setText(_translate("GaoYiWen", "<html><head/><body><p><span style=\" font-size:7pt; color:#0000ff;\">MUST CHECK AFTER EVERY CHOOSE</span></p></body></html>", None))
        self.nameok.setText(_translate("GaoYiWen", "OK", None))
        self.label_2.setText(_translate("GaoYiWen", "<html><head/><body><p><span style=\" color:#000000;\">KEEP MOVING! EARN MORE!</span></p></body></html>", None))
        self.label_3.setText(_translate("GaoYiWen", "<html><head/><body><p><span style=\" font-weight:600; color:#000000;\">SUM MONEY</span></p></body></html>", None))
        self.summoney.setText(_translate("GaoYiWen", "<html><head/><body><p><span style=\" color:#000000;\">$100</span></p></body></html>", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    GaoYiWen = QtGui.QDialog()
    ui = Ui_GaoYiWen()
    ui.setupUi(GaoYiWen)
    GaoYiWen.show()
    sys.exit(app.exec_())

